# Generated by Django 3.2 on 2021-04-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallerymodel',
            options={'verbose_name': 'gallery', 'verbose_name_plural': 'galleries'},
        ),
        migrations.AlterModelOptions(
            name='staffmodel',
            options={'verbose_name': 'staff', 'verbose_name_plural': 'staff'},
        ),
        migrations.RemoveField(
            model_name='gallerymodel',
            name='images',
        ),
        migrations.RemoveField(
            model_name='staffmodel',
            name='title',
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='text',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='gallerymodel',
            name='image',
            field=models.ImageField(default=1, upload_to='gallery'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gallerymodel',
            name='text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='staffmodel',
            name='name',
            field=models.CharField(default=5, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bannermodel',
            name='image',
            field=models.ImageField(upload_to='banners'),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='image',
            field=models.ImageField(upload_to='news'),
        ),
        migrations.AlterField(
            model_name='staffmodel',
            name='position',
            field=models.CharField(max_length=50),
        ),
    ]
