# Generated by Django 3.2 on 2021-04-18 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_newsmodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='description',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
