# Generated by Django 3.2 on 2021-04-18 11:03

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20210418_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
