# Generated by Django 3.2 on 2021-04-25 04:32

from django.db import migrations, models
import posts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_newsmodel_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerymodel',
            name='image',
            field=models.ImageField(upload_to='gallery', validators=[posts.validators.clean_picture]),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='image',
            field=models.ImageField(upload_to='news', validators=[posts.validators.clean_picture]),
        ),
    ]
