# Generated by Django 3.2 on 2021-04-25 10:16

from django.db import migrations, models
import posts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20210425_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='image',
            field=models.ImageField(upload_to='news', validators=[posts.validators.news_picture]),
        ),
        migrations.AlterField(
            model_name='staffmodel',
            name='image',
            field=models.ImageField(upload_to='staff', validators=[posts.validators.staff_picture]),
        ),
    ]
