# Generated by Django 3.2 on 2021-04-27 03:50

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20210425_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannermodel',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('cover', '430x360', adapt_rotation=False, allow_fullsize=False, free_crop=True, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AddField(
            model_name='gallerymodel',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('cover', '430x360', adapt_rotation=False, allow_fullsize=False, free_crop=True, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('cover', '430x360', adapt_rotation=False, allow_fullsize=False, free_crop=True, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AddField(
            model_name='staffmodel',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('cover', '430x360', adapt_rotation=False, allow_fullsize=False, free_crop=True, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='gallerymodel',
            name='text',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
