# Generated by Django 3.2 on 2021-05-02 04:31

from django.db import migrations, models
import posts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20210429_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmodel',
            name='surname',
        ),
        migrations.AlterField(
            model_name='gallerymodel',
            name='image',
            field=models.ImageField(upload_to='gallery', validators=[posts.validators.clean_picture]),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='image',
            field=models.ImageField(upload_to='news', validators=[posts.validators.news_picture]),
        ),
        migrations.AlterField(
            model_name='staffmodel',
            name='image',
            field=models.ImageField(upload_to='staff', validators=[posts.validators.staff_picture]),
        ),
    ]
